name: Feature request
description: Suggest an idea for this project.
title: "[Feature Request]: "
labels: ["enhancement"]

body:
  - type: textarea
    attributes:
      label: What feature do you want?
      description: Tell us about your feature you want
    validations:
      required: true